--比赛信息表--
CREATE TABLE T_MATCH (
MATCH_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
MATCH_NO VARCHAR(20) UNIQUE KEY  NOT NULL,
MATCH_TYPE VARCHAR(50) NOT NULL,
HOME_TEAM_NO	VARCHAR(20) NOT NULL,
GUEST_TEAM_NO	VARCHAR(20) NOT NULL,
HOME_GOALS	int ,
GUEST_GOALS	int ,
PLACE	VARCHAR(50) ,
WEATHER	VARCHAR(20) ,
START_TIME	VARCHAR(20)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='比赛信息表'
ROW_FORMAT=COMPACT
;

CREATE INDEX M_IDX_MATCH_NO ON T_MATCH (MATCH_NO(20));


--比赛赔率表--
CREATE TABLE T_ODDS(
ODDS_ID INT PRIMARY KEY	NOT NULL AUTO_INCREMENT,
MATCH_NO	VARCHAR(20) NOT NULL	,
O_HOME	DOUBLE ,
O_DRAW	DOUBLE ,
O_AWAY	DOUBLE ,
CONCEDE_POINT	INT ,
O_HOME_2 DOUBLE ,
O_DRAW_2 DOUBLE ,
O_AWAY_2 DOUBLE ,
O_HOME_BF	DOUBLE ,
O_DRAW_BF	DOUBLE ,
O_AWAY_BF	DOUBLE ,
PUBLISH_TIME VARCHAR(20)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='比赛赔率信息表'
ROW_FORMAT=COMPACT;

CREATE INDEX O_IDX_MATCH_NO ON T_ODDS (MATCH_NO(20));

--比赛投注量表--
CREATE TABLE T_BET_AMOUNT(
BET_ID INT PRIMARY KEY	NOT NULL AUTO_INCREMENT,
MATCH_NO	VARCHAR(20) NOT NULL	,
HOME_AMOUNT_BF	DOUBLE ,
DRAW_AMOUNT_BF	DOUBLE ,
AWAY_AMOUNT_BF	DOUBLE ,
HOME_AMOUNT_ST DOUBLE ,
DRAW_AMOUNT_ST DOUBLE ,
AWAY_AMOUNT_ST DOUBLE ,
PUBLISH_TIME VARCHAR(20)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='比赛投注量表'
ROW_FORMAT=COMPACT;

CREATE INDEX B_IDX_MATCH_NO ON T_BET_AMOUNT (MATCH_NO(20));


--联赛信息表--
CREATE TABLE T_LEAGUE (
LEAGUE_ID INT PRIMARY KEY	NOT NULL AUTO_INCREMENT,
LEAGUE_NO	VARCHAR(20) NOT NULL,
LEAGUE_NAME	VARCHAR(50) NOT NULL,
LEAGUE_SHORT_NAME VARCHAR(20) NOT NULL,
COUNTRY VARCHAR(20)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='联赛信息表'
ROW_FORMAT=COMPACT;


--俱乐部信息表--
CREATE TABLE T_CLUB (
CLUB_ID INT PRIMARY KEY	NOT NULL AUTO_INCREMENT,
CLUB_NO	VARCHAR(20) NOT NULL,
CLUB_NAME	VARCHAR(50) NOT NULL,
CLUB_SHORT_NAME	VARCHAR(20) NOT NULL,
LEAGUE_NO	VARCHAR(20) NOT NULL,
LEAGUE_RANKING int
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='俱乐部信息表'
ROW_FORMAT=COMPACT;


-- CREATE TABLE TB_CODE_INT (
-- ID INT PRIMARY KEY	NOT NULL AUTO_INCREMENT,
-- CODETYPE_ID	VARCHAR(20) NOT NULL,
-- CODE_ID	VARCHAR(20) NOT NULL,
-- CODE_DESC VARCHAR(500) NOT NULL
-- );
--
-- CREATE TABLE TB_USER(
-- ID INT PRIMARY KEY	NOT NULL AUTO_INCREMENT,
-- USER_NAME	VARCHAR(20) NOT NULL,
-- PASS_WORD	VARCHAR(32) NOT NULL,
-- EXPIRY_IND	CHAR(1) NOT NULL DEFAULT 'N',
-- LS_LOGIN_DT	TIMESTAMP ,
-- REGISTER_DATE	TIMESTAMP
-- );