/* ** 显示最近两天内，比赛的最新投注信息 ****/

CREATE OR REPLACE VIEW VW_LATEST_BET
AS
SELECT MAX(B.BET_ID) AS BET_ID, B.MATCH_NO
FROM T_BET_AMOUNT B
LEFT JOIN T_MATCH M
ON B.MATCH_NO = M.MATCH_NO
WHERE STR_TO_DATE(M.START_TIME, '%Y-%m-%d %H:%i:%s') > DATE_SUB(NOW(),INTERVAL 2 DAY)
GROUP BY B.MATCH_NO;

/* ** 显示最近两天内，比赛的最新赔率信息 ****/

CREATE OR REPLACE VIEW VW_LATEST_ODDS
AS
SELECT MAX(O.ODDS_ID) AS ODDS_ID, O.MATCH_NO
FROM T_ODDS O
LEFT JOIN T_MATCH M
ON O.MATCH_NO = M.MATCH_NO
WHERE STR_TO_DATE(M.START_TIME, '%Y-%m-%d %H:%i:%s') > DATE_SUB(NOW(),INTERVAL 2 DAY)
GROUP BY O.MATCH_NO;


/* ** 显示最近两天内，所有比赛的最新投注量 详情：****/
CREATE OR REPLACE VIEW VW_LATEST_BET_DETAIL
AS
SELECT
B.MATCH_NO AS MATCH_NO,
(SELECT L.LEAGUE_SHORT_NAME FROM T_LEAGUE L WHERE L.LEAGUE_NO = M.MATCH_TYPE) AS LEAGUE_NAME,
(SELECT T.CLUB_NAME FROM T_CLUB T WHERE T.CLUB_NO = M.HOME_TEAM_NO) AS HOME_TEAM,
(SELECT T.CLUB_NAME FROM T_CLUB T WHERE T.CLUB_NO = M.GUEST_TEAM_NO) AS GUEST_TEAM,
M.START_TIME AS START_TIME,
O.O_HOME AS HOME_ODDS,
O.O_DRAW AS DRAW_ODDS,
O.O_AWAY AS AWAY_ODDS,
O.CONCEDE_POINT AS CONCEDE_POINT,
O.O_HOME_2 AS HOME_ODDS_2,
O.O_DRAW_2 AS DRAW_ODDS_2,
O.O_AWAY_2 AS AWAY_ODDS_2,
B.HOME_AMOUNT_BF AS HOME_AMOUNT_BF,
B.DRAW_AMOUNT_BF AS DRAW_AMOUNT_BF,
B.AWAY_AMOUNT_BF AS AWAY_AMOUNT_BF,
B.HOME_AMOUNT_ST AS HOME_AMOUNT_ST,
B.DRAW_AMOUNT_ST AS DRAW_AMOUNT_ST,
B.AWAY_AMOUNT_ST AS AWAY_AMOUNT_ST,
B.HOME_AMOUNT_BF+B.DRAW_AMOUNT_BF+B.AWAY_AMOUNT_BF AS TOTAL_BF,
B.HOME_AMOUNT_ST+B.DRAW_AMOUNT_ST+B.AWAY_AMOUNT_ST AS TOTAL_ST,
-- B.HOME_AMOUNT_BF*ifnull(O.O_HOME,0)-(B.HOME_AMOUNT_BF+B.DRAW_AMOUNT_BF+B.AWAY_AMOUNT_BF) AS HOME_profit_BF,
-- B.DRAW_AMOUNT_BF*ifnull(O.O_HOME,0)-(B.HOME_AMOUNT_BF+B.DRAW_AMOUNT_BF+B.AWAY_AMOUNT_BF) AS HOME_profit_BF,
-- B.AWAY_AMOUNT_BF*ifnull(O.O_AWAY,0)-(B.HOME_AMOUNT_BF+B.DRAW_AMOUNT_BF+B.AWAY_AMOUNT_BF) AS HOME_profit_BF,
FORMAT((B.HOME_AMOUNT_ST+B.DRAW_AMOUNT_ST+B.AWAY_AMOUNT_ST) - B.HOME_AMOUNT_ST*IFNULL(O.O_HOME,0),2) AS HOME_PROFIT_ST,
FORMAT((B.HOME_AMOUNT_ST+B.DRAW_AMOUNT_ST+B.AWAY_AMOUNT_ST) - B.DRAW_AMOUNT_ST*IFNULL(O.O_DRAW,0),2) AS DRAW_PROFIT_ST,
FORMAT((B.HOME_AMOUNT_ST+B.DRAW_AMOUNT_ST+B.AWAY_AMOUNT_ST) - B.AWAY_AMOUNT_ST*IFNULL(O.O_AWAY,0),2) AS AWAY_PROFIT_ST,
CONCAT(FORMAT(B.HOME_AMOUNT_BF/(B.HOME_AMOUNT_BF+B.DRAW_AMOUNT_BF+B.AWAY_AMOUNT_BF), 4)*100, '%') AS HOME_BF_PER,
CONCAT(FORMAT(B.DRAW_AMOUNT_BF/(B.HOME_AMOUNT_BF+B.DRAW_AMOUNT_BF+B.AWAY_AMOUNT_BF), 4)*100, '%') AS DRAW_BF_PER,
CONCAT(FORMAT(B.AWAY_AMOUNT_BF/(B.HOME_AMOUNT_BF+B.DRAW_AMOUNT_BF+B.AWAY_AMOUNT_BF), 4)*100, '%') AS AWAY_BF_PER,
CONCAT(FORMAT(B.HOME_AMOUNT_ST/(B.HOME_AMOUNT_ST+B.DRAW_AMOUNT_ST+B.AWAY_AMOUNT_ST), 4)*100, '%') AS HOME_ST_PER,
CONCAT(FORMAT(B.DRAW_AMOUNT_ST/(B.HOME_AMOUNT_ST+B.DRAW_AMOUNT_ST+B.AWAY_AMOUNT_ST), 4)*100, '%') AS DRAW_ST_PER,
CONCAT(FORMAT(B.AWAY_AMOUNT_ST/(B.HOME_AMOUNT_ST+B.DRAW_AMOUNT_ST+B.AWAY_AMOUNT_ST), 4)*100, '%') AS AWAY_ST_PER

FROM VW_LATEST_BET VB
LEFT JOIN T_BET_AMOUNT B
ON B.BET_ID = VB.BET_ID
LEFT JOIN VW_LATEST_ODDS VO ON
VO.MATCH_NO = VB.MATCH_NO
LEFT JOIN T_ODDS O
ON VO.ODDS_ID=O.ODDS_ID
LEFT JOIN T_MATCH M
ON M.MATCH_NO = VB.MATCH_NO
ORDER BY M.START_TIME DESC
;




